### ISSUE TITLE
'TensorVariable' object has no attribute '_shape'

### ISSUE THREAD

**Issue by jocicmarko** [raghakot/keras-resnet#1]
Hey Ragha, thank you for sharing this, nice job!

I'm having difficulties running your example. I'm using latest versions of Keras and Theano.

```
File "train_resnet.py", line 139, in <module>
    model = resnet()
  File "resnet.py", line 110, in resnet
    block1 = _residual_block(block_fn, nb_filters=64, repetations=3, is_first_layer=True)(pool1)
  File "resnet.py", line 93, in f
    input = block_function(nb_filters=nb_filters, init_subsample=init_subsample)(input)
  File "resnet.py", line 50, in f
    return _shortcut(input, residual)
  File "resnet.py", line 72, in _shortcut
    stride_width = input._shape[2].value / residual._shape[2].value
AttributeError: 'TensorVariable' object has no attribute '_shape'
```

Would you mind letting me know if have to do anything more in order to run your implementation of ResNet?

Thank you in advance,
Marko

**Comment by raghakot** [comment]
I tested it with tensor flow. I wonder if it needs more changes to work with theano. I will try it out and let u know soon.

Sent from Outlook Mobile<https://aka.ms/qtex0l>




On Sat, Apr 23, 2016 at 3:32 AM -0700, "Marko Jocić" <notifications@github.com<mailto:notifications@github.com>> wrote:


Hey Ragha, thank you for sharing this, nice job!

I'm having difficulties running your example. I'm using latest versions of Keras and Theano.

File "train_resnet.py", line 139, in <module>
    model = resnet()
  File "resnet.py", line 110, in resnet
    block1 = _residual_block(block_fn, nb_filters=64, repetations=3, is_first_layer=True)(pool1)
  File "resnet.py", line 93, in f
    input = block_function(nb_filters=nb_filters, init_subsample=init_subsample)(input)
  File "resnet.py", line 50, in f
    return _shortcut(input, residual)
  File "resnet.py", line 72, in _shortcut
    stride_width = input._shape[2].value / residual._shape[2].value
AttributeError: 'TensorVariable' object has no attribute '_shape'


Would you mind letting me know if have to do anything more in order to run your implementation of ResNet?

Thank you in advance,
Marko

-

**Comment by raghakot** [comment]
This should now be fixed. Try and let me know.

**Comment by jocicmarko** [comment]
I appreciate your effort, I also fixed the issue myself.

Thanks again and best regards,
Marko
